require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.2.2

  Exclude:
    - 'bin/*'
    - 'tmp/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/bundle/**/*'

  NewCops: enable

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false
